### PR TITLE
Update for new mobs and entity classes in 1.11

### PR DESCRIPTION
**Pull request by KovuTheHusky**
Entity classes were cleaned up for 1.11 and sub-entities were put into their own classes. I've also added mobs such as the Evoker, Vex, and Vindicator.

I also updated the icon for vanillahorse and various minecarts.

### CODE REVIEW

**Comment by KovuTheHusky** [comment]
This also closes #14.

**Comment by KovuTheHusky** [comment]
It may be better to simply use the entity name if that is at all possible due to issues with inheritance, such as #9. That would require a rewrite though. Is there any technical reason this isn't a possibility?

**Comment by wioxjk** [comment]
@mikeprimm 
Can you please merge this?

**Comment by wioxjk** [comment]
@KovuTheHusky 
Is it possible that you can compile the .jar and post it somewhere? Would be nice with an up-to-date plugin to dynmap :)

**Comment by KovuTheHusky** [comment]
The best thing would be for @mikeprimm to accept this PR - it's his project after all. If you want an up to date jar for now you should be able to clone the repo and run `mvn install` to make your own. I don't want to overstep and start distributing it myself.

**Comment by wioxjk** [comment]
@KovuTheHusky 
Well, I know that @mikeprimm ranted about that noone helped him in this project a few month ago. And when someone takes the time to improve - nothing happends.

I am not familliar with "nvm" actually, I guess it is just to run it in the catalogue?

**Comment by mikeprimm** [comment]
@KovuTheHusky Thanks for the update, as always
@wioxjk The 'rant' was about the presumptuousness of an over-entitled prick who seems to think that someone who has donated literally thousands of hours of development time over the past 6 years for no pay to produce mods that have always been available for free owes him ANYTHING (hint: I don't).  You don't get to get things for free and then complain about them not being what you want - particularly when their source is available for free, and you're able to make what you want yourself (given suitable time, talent, and <gasp> motivation).

**Comment by wioxjk** [comment]
@mikeprimm 
I totally agree with you! I do not know how many hours you have spent to make dynmap and all the plugins to it - but it is propably alot! And that kids attitude was not the best.
But I mean, @KovuTheHusky wanted to merge his update over a month ago. That is a pretty long time...

Anyway, thanks for the merge!

**Pull request merged**
